# Generated by Django 5.1.1 on 2024-09-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imageupload_doctor_comment_alter_imageupload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='user',
        ),
    ]
