# Generated by Django 5.1.1 on 2024-09-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recommendationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='request_status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
