# Generated by Django 5.1.1 on 2024-09-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imageupload_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationrequest',
            name='disease_predict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
