# Generated by Django 5.1.1 on 2024-09-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EyeImage',
        ),
    ]
