# Generated by Django 5.1.1 on 2024-09-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
